# Generated by Django 6.1 on 2026-08-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUpload',
        ),
    ]
